{"uuid":"f9c9b30d-d4c6-497a-98c3-cb04d548cf8e","historyId":"504b5a50424451e5090122a37b242259","fullName":"Collection.AutoAssign.Issuetype.UpdateIssueType.UpdateIssueType_404","labels":[{"name":"package","value":"Collection.AutoAssign.Issuetype.UpdateIssueType"},{"name":"testClass","value":"Collection.AutoAssign.Issuetype.UpdateIssueType"},{"name":"testMethod","value":"UpdateIssueType_404"},{"name":"parentSuite","value":"Messenger Backend API Test"},{"name":"suite","value":"Update Issue type"},{"name":"subSuite","value":"Collection.AutoAssign.Issuetype.UpdateIssueType"},{"name":"host","value":"ennymax"},{"name":"thread","value":"29524@ennymax.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"An Endpoint to Update issue type 403"},{"name":"severity","value":"critical"}],"links":[],"name":"UpdateIssueType_404","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected: <500> but was: <404>","trace":"org.opentest4j.AssertionFailedError: expected: <500> but was: <404>\r\n\tat org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)\r\n\tat org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)\r\n\tat org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)\r\n\tat org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)\r\n\tat org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)\r\n\tat Collection.AutoAssign.Issuetype.UpdateIssueType.UpdateIssueType_404(UpdateIssueType.java:55)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)\r\n\tat org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:808)\r\n\tat org.testng.TestRunner.run(TestRunner.java:603)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:429)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:326)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1169)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1092)\r\n\tat org.testng.TestNG.run(TestNG.java:1060)\r\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)\r\n\tat org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)\r\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)\r\n"},"stage":"finished","description":"An Endpoint to Update issue type 403","steps":[],"attachments":[{"name":"Request","source":"995bc128-4a7f-4645-a981-074427556a96-attachment.html","type":"text/html"},{"name":"Request","source":"c110dd3d-58c5-4fb6-8cbb-f3b5a14193df-attachment.html","type":"text/html"},{"name":"HTTP/1.1 200 OK","source":"9b5f6d8e-3c7c-4ab9-9ce5-784e407f1f14-attachment.html","type":"text/html"},{"name":"HTTP/1.1 200 OK","source":"53dd87ab-3726-4f97-aff9-81992a5b76b5-attachment.html","type":"text/html"},{"name":"Request","source":"04e9e3e4-127f-4449-ae0d-73d848f9cdeb-attachment.html","type":"text/html"},{"name":"HTTP/1.1 500 Internal Server Error","source":"e9a6f544-5d77-428a-876f-7ae8aac0f55d-attachment.html","type":"text/html"}],"parameters":[],"start":1645431335618,"stop":1645431339439}